// Auto-generated binary data by the Projucer
// Source file: ../Localization/PresetInfo-en.json

#include "PresetInfo-en.h"

static constexpr unsigned char PresetInfoen_json_local[] =
"{\n"
"\t\"authors\":{\n"
"\t\t\"Dresage\" :{\n"
"\t\t\t\"name\" : \"Dresage\",\n"
"\t\t\t\"url\" : \"https://bit.ly/2NvWekk\"\n"
"\t\t},\n"
"\t\t\"Bad\" : {\n"
"\t\t\t\"name\" : \"Bad Snacks\",\n"
"\t\t\t\"url\" : \"https://bit.ly/3t7dg91\"\n"
"\t\t}\n"
"\t},\n"
"\t\"presets\":{\n"
"\t\"pancake\":{\n"
"\t\t\"description\" : \"Sweet syrupy drums that will bring a unique texture to your beats\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"biscuit\" : {\n"
"\t\t\"description\" : \"Puffy kicks and fizzy, quirky percussion gives you all the tools to make beats that don't skip the carbs\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"scone\" : {\n"
"\t\t\"description\" : \"Drums that hit but stay round and doughy on impact\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"electro\":{\n"
"\t\t\"description\" : \"808 kicks and snappy snares are the foundation of any track\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"cookin\" : {\n"
"\t\t\"description\" : \"Clicky and clacky metallic found sounds that found their way to you!\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"strings\" : {\n"
"\t\t\"description\" : \"Beautiful violin chords you can play with one finger\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"stringsss\" : {\n"
"\t\t\"description\" : \"Beautiful stretched violin chords you can play with one finger\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"buffet\" : {\n"
"\t\t\"description\" : \"A collection of female vocal pop runs and adlibs that fizz, crunch and manipulate pitch/formant\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"jello\" : {\n"
"\t\t\"description\" : \"Female vocals with throwback 2000's soul and all the boyband era feels\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"funfetti\" : {\n"
"\t\t\"description\" : \"Female group melodies in harmony. A technicolor good time!\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"lit\" : {\n"
"\t\t\"description\" : \"Round analog synth sound for leads or bass\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"meringue\" : {\n"
"\t\t\"description\" : \"A silky whipped vocal instrument you can play yourself!\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"meringueee\" : {\n"
"\t\t\"description\" : \"A stretched silky whipped vocal instrument you can play yourself!\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"pluck\" : {\n"
"\t\t\"description\" : \"Lovely synth sound for melody lines\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"saw\" : {\n"
"\t\t\"description\" : \"Essential sawtooth synth sound\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"sine\" : {\n"
"\t\t\"description\" : \"The lovely simple tones of a sinewave\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"smooth\" : {\n"
"\t\t\"description\" : \"Smooth falloff on this synth tone\",\n"
"\t\t\"author\" : \"Bad\" \n"
"\t},\n"
"\t\"square\" : {\n"
"\t\t\"description\" : \"When you need more, reach for the square wave\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"trapezoid\" : {\n"
"\t\t\"description\" : \"A cross between a traingle and a square wave\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"triangle\" : {\n"
"\t\t\"description\" : \"Lovely bell like tones from this triangle\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"zap\" : {\n"
"\t\t\"description\" : \"Cut through the mix with this buzzy synth\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"p-bass\":{\n"
"\t\t\"description\" : \"Fill out the bottom end with this classic bass guitar\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"synth\":{\n"
"\t\t\"description\" : \"Analog low end\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t}\n"
"\t}\n"
"}";

const char* PresetInfoen_json = (const char*) PresetInfoen_json_local;
