// Auto-generated binary data by the Projucer
// Source file: ../Localization/PresetInfo-en.json

#include "PresetInfo-en.h"

static constexpr unsigned char PresetInfoen_json_local[] =
"{\n"
"\t\"authors\":{\n"
"\t\t\"Dresage\" :{\n"
"\t\t\t\"name\" : \"Dresage\",\n"
"\t\t\t\"url\" : \"https://bit.ly/2NvWekk\"\n"
"\t\t},\n"
"\t\t\"Bad\" : {\n"
"\t\t\t\"name\" : \"Bad Snacks\",\n"
"\t\t\t\"url\" : \"https://bit.ly/3t7dg91\"\n"
"\t\t}\n"
"\t},\n"
"\t\"presets\":{\n"
"\t\"pancake\":{\n"
"\t\t\"description\" : \"Description for pancake\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"biscuit\" : {\n"
"\t\t\"description\" : \"Description for biscuit\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"scone\" : {\n"
"\t\t\"description\" : \"Description for scone\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"electro\":{\n"
"\t\t\"description\" : \"Description for electro\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"cookin\" : {\n"
"\t\t\"description\" : \"Foley sounds from power tools to the kitchen\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"stringsss\" : {\n"
"\t\t\"description\" : \"Beautiful chords you can play with one finger\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"lit\" : {\n"
"\t\t\"description\" : \"Round analog synth sound with arpeggiation\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"saw\" : {\n"
"\t\t\"description\" : \"Description for saw\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"sine\" : {\n"
"\t\t\"description\" : \"Description for sine\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"square\" : {\n"
"\t\t\"description\" : \"Description for square\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"trapezoid\" : {\n"
"\t\t\"description\" : \"Description for trapezoid\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"triangle\" : {\n"
"\t\t\"description\" : \"Description for triangle\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"zap\" : {\n"
"\t\t\"description\" : \"Description for zap\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"p-bass\":{\n"
"\t\t\"description\" : \"Description for p-bass\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t}\n"
"\t}\n"
"}";

const char* PresetInfoen_json = (const char*) PresetInfoen_json_local;
