// Auto-generated binary data by the Projucer
// Source file: ../Localization/PresetInfo-es.json

#include "PresetInfo-es.h"

static constexpr unsigned char PresetInfoes_json_local[] =
"{\n"
"\t\"authors\":{\n"
"\t\t\"Dresage\" :{\n"
"\t\t\t\"name\" : \"Dresage\",\n"
"\t\t\t\"url\" : \"https://bit.ly/2NvWekk\"\n"
"\t\t},\n"
"\t\t\"Bad\" : {\n"
"\t\t\t\"name\" : \"Bad Snacks\",\n"
"\t\t\t\"url\" : \"https://bit.ly/3t7dg91\"\n"
"\t\t}\n"
"\t},\n"
"\t\"presets\":{\n"
"\t\"pancake\":{\n"
"\t\t\"description\" : \"Dulces tambores que aportar\xc3\xa1n textura a tus ritmos\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"biscuit\" : {\n"
"\t\t\"description\" : \"Patadas hinchadas y percusi\xc3\xb3n burbujeante\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"scone\" : {\n"
"\t\t\"description\" : \"Tambores que golpean con impacto\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"electro\":{\n"
"\t\t\"description\" : \"808 patadas y trampas \xc3\xa1giles son la base de cualquier pista\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"cookin\" : {\n"
"\t\t\"description\" : \"Sonidos met\xc3\xa1licos clicky y clacky\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"strings\" : {\n"
"\t\t\"description\" : \"Hermosos acordes de viol\xc3\xadn que puedes tocar con un dedo\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"stringsss\" : {\n"
"\t\t\"description\" : \"Hermosos acordes de viol\xc3\xadn estirados que puedes tocar con un dedo\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"buffet\" : {\n"
"\t\t\"description\" : \"Una colecci\xc3\xb3n de corridas y adlibs de pop vocal femenino\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"jello\" : {\n"
"\t\t\"description\" : \"Voces femeninas con alma de 2000\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"funfetti\" : {\n"
"\t\t\"description\" : \"Melod\xc3\xad""as grupales femeninas en armon\xc3\xad""a\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"lit\" : {\n"
"\t\t\"description\" : \"Sonido de sintetizador anal\xc3\xb3gico redondo para solistas o bajos\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"meringue\" : {\n"
"\t\t\"description\" : \"\xc2\xa1Un instrumento vocal sedoso que puedes tocar t\xc3\xba mismo!\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"meringueee\" : {\n"
"\t\t\"description\" : \"\xc2\xa1Un instrumento vocal sedoso que puedes tocar t\xc3\xba mismo!\",\n"
"\t\t\"author\" : \"Dresage\"\n"
"\t},\n"
"\t\"pluck\" : {\n"
"\t\t\"description\" : \"Sonido de sintetizador para l\xc3\xadneas mel\xc3\xb3""dicas\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"saw\" : {\n"
"\t\t\"description\" : \"Sonido de sintetizador de diente de sierra esencial\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"sine\" : {\n"
"\t\t\"description\" : \"Los hermosos tonos simples de una onda sinusoidal\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"smooth\" : {\n"
"\t\t\"description\" : \"Ca\xc3\xad""da suave en este tono de sintetizador\",\n"
"\t\t\"author\" : \"Bad\" \n"
"\t},\n"
"\t\"square\" : {\n"
"\t\t\"description\" : \"Cuando necesite m\xc3\xa1s, busque la onda cuadrada\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"trapezoid\" : {\n"
"\t\t\"description\" : \"Un cruce entre un traingle y una onda cuadrada\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"triangle\" : {\n"
"\t\t\"description\" : \"Preciosos tonos de campana de este tri\xc3\xa1ngulo\",\n"
"\t\t\"author\" : \"\" \n"
"\t},\n"
"\t\"zap\" : {\n"
"\t\t\"description\" : \"Corta la mezcla con este vibrante sintetizador\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"p-bass\":{\n"
"\t\t\"description\" : \"Completa el extremo inferior con este bajo cl\xc3\xa1sico\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t},\n"
"\t\"synth\":{\n"
"\t\t\"description\" : \"Gama baja anal\xc3\xb3gica\",\n"
"\t\t\"author\" : \"Bad\"\n"
"\t}\n"
"\t}\n"
"}";

const char* PresetInfoes_json = (const char*) PresetInfoes_json_local;
